### ISSUE TITLE
Error when running fakegir.py - KeyError: 'name'

### ISSUE THREAD

**Issue by garlic64** [strycore/fakegir#24]
I'm attempting to install fakegir on Ubuntu MATE.
When I run fakegir.py, I get this error:
```
Parsing /usr/share/gir-1.0/Atspi-2.0.gir 
    Traceback (most recent call last):
      File "./fakegir.py", line 434, in <module>
        generate_fakegir()
      File "./fakegir.py", line 425, in generate_fakegir
        fakegir_content = parse_gir(gir_path)
      File "./fakegir.py", line 382, in parse_gir
        namespace_content = extract_namespace(namespace)
      File "./fakegir.py", line 351, in extract_namespace
        get_parameters(element),
      File "./fakegir.py", line 117, in get_parameters
        param_type = get_parameter_type(param)
      File "./fakegir.py", line 76, in get_parameter_type
        param_type = elem_property.attrib['name']
      File "src/lxml/etree.pyx", line 2457, in lxml.etree._Attrib.__getitem__
    KeyError: 'name'
```
Any ideas on how to fix this?

**Comment by ShevoPramide** [comment]
i hope that anyone can  find a solution for this issue

**Comment by kastixx** [comment]
Have this ever worked?
The script fails on an entry in `Atspi-2.0.gir`:

```xml
        <parameter name="server" transfer-ownership="none">
          <doc xml:space="preserve">the server</doc>
          <type c:type="DBusServer*"/>
        </parameter>
```

(`<type>` tag for `server` parameter does not have a `name` attribute here)

which corresponds to the first argument of this function in `at-spi2-core`:

```c
void atspi_dbus_server_setup_with_g_main (DBusServer *server, GMainContext *context);
```

`DBusServer` is a type in `dbus-1.0` library which does not have a corresponding gir file for introspection. For some reason the author of this function did use this class instead of fully introspectable `GDBusServer` wrapper from GLib.

I think this can be worked around though.

**Comment by garlic64** [comment]
The work-around worked for me. I ran fakegir.py and there were no errors. Now I have auto-complete available for GTK+ 3 in the IDE that I use. Thanks kastixx.

**Comment by kastixx** [comment]
@garlic64 No problem. Please remember to switch to master when this patch is merged to keep up with updates.
